### PR TITLE
feat: ESM, `setAtKeyPath`

### PR DESCRIPTION
**Pull request by brettz9**
### User-facing

- Enhancement: ESM (^12.22.0 || ^14.17.0 || >=16.0.0)
- Enhancement: Expose `Typeson.setAtKeyPath`

### Dev-facing

- chore: switches to c8 from nyc for ESM compatibility
- npm: Update devDeps.

Hi there... Just wanted to confirm you're ok with the changes here (and for the registry alpha), as it is a breaking change (bumping major version with `engines` bump), in order to add true ESM support (while still providing a proper UMD export). Also re-exports a utility within the project that hadn't been reexported previously.

### CODE REVIEW

**Review by dfahlander — APPROVED** [review]
Thanks for requesting a review. I think the library is in fact maintained by you nowadays but it's nice to get the option to see what's happening with it.

I'm not aware of all the tools used, but from what I can understand, I couldn't see any problems with the changes. I've learned it's a complex thing with getting dual exports right. I think this commit seems to do it right. Maybe it could be a bit confusing that the umd export has the cjs extension, but it's indeed a cjs also so it's probably ok.

If you want, we could transfer typeson and typeson registry to your github account? I'd still like to be a contributor but seems you are the real maintainer of the library so it's probably more right you take it over. If you want that, I can request the repositories to be transferred to your personal or organisational github account. Please let me know if you want that!

David

**Comment by brettz9** [comment]
> Thanks for requesting a review. I think the library is in fact maintained by you nowadays but it's nice to get the option to see what's happening with it.
> 
> I'm not aware of all the tools used, but from what I can understand, I couldn't see any problems with the changes. I've learned it's a complex thing with getting dual exports right. I think this commit seems to do it right. Maybe it could be a bit confusing that the umd export has the cjs extension, but it's indeed a cjs also so it's probably ok.

Yes, sure. I've been working on a number of such projects previously, and although there can be some pitfalls, I'm pretty confident I've generally gotten the hang of it. I've tested with linked copies of `typeson-registry` using `typeson` (and updated my array buffer fork to use true ESM already which these are able to consume fine).

Re: the cjs extension, yeah, with genuine ESM, there is the issue that Node will insist that with `type: "module"`, the "js" extension may only be understood as ESM and the "cjs" as CommonJS, but there's another issue which is not Node-specific, but important to know--Webpack will complain if it find CJS exports within files in the package besides the "cjs" type--even when Node is not using them. I had to change a release in this manner previously for this reason. The only other option I think is using "mjs" for all files for ESM, and using `type: commonjs`, but this seems to be a real exception, and frankly a little unpleasant tbh, imo.

> If you want, we could transfer typeson and typeson registry to your github account? I'd still like to be a contributor but seems you are the real maintainer of the library so it's probably more right you take it over. If you want that, I can request the repositories to be transferred to your personal or organisational github account. Please let me know if you want that!

Unless you wish more distance from a project you are not able to be as active with, there's no need to do so on my account. Even the asynchronous feature I added really followed the pattern you had set up, and many of my other changes feel more incremental. I think the core remains your baby. And I've appreciated your openness and responsiveness in collaboration all along the way, by the way, so no worries about me feeling the need to go it alone, though whatever approach you want to take is fine.

In any case though, I should take the opportunity to ask one other question... With `typeson-registry`, you had asked me to stay on the alpha releases way back, and we've been using those. With some real breaking changes (at least as far as a minimum Node version) and with some people perhaps having come to rely on the alpha channel, I am wondering whether you think it might be time to just release as a major bump, and if there is a need in the future (e.g., if you wish to rewrite the project), we could do additional such bumps?

**Comment by brettz9** [comment]
I could also release what we have as 1.0.0 (if people might wish to peg to that) and then switch to 2.0.0 for ESM.

And one other item... what do you think of avoiding the default export (also for typeson proper) to allow tree-shaking? I think this may help us move to using `exports`. We'd just need to rename either the `undef` type or preset since they'd otherwise clash with the same name on the exports. I don't know for sure I'd get to doing this, but wanted to ask if ok.

Thanks!

**Comment by brettz9** [comment]
> I also want to share with you one thing I've been doing lately - I have been laborating with a simplified approach of typeson. However, it feels as such a major change without backward compability - and with lesser features (right now at least) - so I don't know if it would ever fit as a new major version of typeson or not. As of current, it's more as an experiment - still usable for what I'm working on now. If it's too much of a change to ever incorporate it into typeson - and that would be fine - it could instead be released as its own library at some point (typeson-simplified?). However, If you'd feel that this would be an approach for a new version of typeson and typeson-registry, let me know. I totally understand if you do not think it would be a fit - you have libraries that rely on the current approach and backward compability is probably important for your libraries. It might be the case that this kind of library that typeson is, that actually produces a storage format, is not suitable for making such changes in the protocol between new versions but rather be released with a new name.

As your projects, I think you should do however you see fit (as long as following semver).

I could always fork them as needed. `IndexedDBShim` is pinned safely to specific patch versions even.

Whether I would want to use it would depend on the nature of the compatibility. I would be open to using it if it could come to preserving the same functionality (and passing tests) even if requiring API changes (there are just a few lines of code we have accessing the API in `IndexedDBShim` anyways).

But as a storage format, yes, it would be a serious breaking change for users, but that is something I have had to break before (in a major version). If there is a compelling reason to do so, e.g., because of the format being more optimal in storage, allowing for storage of types of data not yet allowed, or even fixing bugs I don't have the energy to resolve myself, I think it would be worth it. (I really wish I could have fixed the two bugs we still have for our present users, but lacking in energy to dig into it and find a way to resolve.)

> The code of it is in [TypesonSimplified.ts](https://github.com/dreambasejs/dreambase/blob/030879dc7561bfb82c6a107c95e9aa387991535f/libs/dreambase-library/src/typeson-simplified/TypesonSimplified.ts). I'm currently using it in dexie-cloud for transferring and storing rich types. The main difference is that the $type info isn't pulled up to the root object but contained where it applies. 

It sounds like an appealing approach, though I really have never had quite as facile (in the good sense of the word) of a handle on the design choices (and having brain fog doesn't help).

But does sound good to my limited sense. Should be easier for consumers to debug I imagine, seeing the types right there and all.

Off topic, but in reflecting on big picture issues, imagine it should be interesting to have JSON Schema and/or TypeScript data on the kind of data structures that might be produced in storing specific types.

> Also, the current implementation rides upon existing JSON.stringify() only so currently no support for encapsulate/revive but that could be changed even if keeping the format for typedefs and output.

Cool. Guess there is `toJSON` a custom version of which could be injected at runtime if the native object did not have one if that makes any sense.

Still planning to support circular objects?

**Pull request merged**
